server:
  port: 8088

spring:
  application:
    name: cache-demo
  datasource:
    url: jdbc:mysql://127.0.0.1/cache_demo?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource


